### ISSUE TITLE
Delay/Fail to Post 

### ISSUE THREAD

**Issue by barterjoe** [frappe/frappejs#58]
Hello, I noticed on some screens there is no feedback when submitting data. For example, importing clients there is no loading wheel and page refresh is required to update. 
Let me know if I can assist. I am not a programmer but can learn fast. 

 Installed Apps
ERPNext: v10.x.x-develop (02a40e9) (develop)

Frappe Framework: v10.x.x-develop (947f409) (develop)

**Comment by netchampfaris** [comment]
I think you have got the repository wrong. Please open issues related to Frappe Framework on https://github.com/frappe/frappe
